# RULE BASED SENTIMENT

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Youtube_sentiment.csv")
df

,Channel_Sumber,Author,Comment_Final,Likes,Time,Tipe_Komentar
0,Jagat Review,@CheverrlynAdyba,link beli chamon pro 5g,0,2026-03-21 13:04:52+00:00,Utama
1,Jagat Review,@caesarrizkie9742,ngomongin rog kah kamera turun lihat review ca...,0,2026-03-17 20:41:02+00:00,Utama
2,Jagat Review,@adealfian664,user samsung one ui ui enak ui ui if you can t...,0,2026-03-13 23:27:54+00:00,Utama
3,Jagat Review,@RsyatLyioz,tecno pova ultra 5g,0,2026-03-12 20:11:30+00:00,Utama
4,Jagat Review,@CitraUtut,tolong buatin rekomendasi lebaran,2,2026-03-02 23:12:23+00:00,Utama
...,...,...,...,...,...,...
7194,Gadgetin,@imnaps,akhirnyaa rekomendasi,1,2025-12-07 09:27:42+00:00,Utama
7195,Gadgetin,@MOLEND95,first wkwkkw,0,2025-12-07 09:27:40+00:00,Utama
7196,Gadgetin,@m.abidalbaqie9527,party popper party popper,0,2025-12-07 09:27:40+00:00,Utama
7197,Gadgetin,@tayaaasy8007,sampe skrng kebel loudly crying face loudly cr...,0,2025-12-07 09:27:39+00:00,Utama
7198,Gadgetin,@adhapriyo,pin mass grinning face with sweat,2,2025-12-07 09:27:30+00:00,Utama

In [3]:
positif = {

    # umum
    "bagus",
    "mantap",
    "keren",
    "oke",
    "baik",
    "stabil",
    "cepat",
    "halus",
    "lancar",
    "responsif",

    # harga
    "murah",
    "worth",
    "worthit",
    "terjangkau",
    "hemat",

    # performa
    "kencang",
    "ngebut",
    "smooth",
    "powerful",
    "responsif",

    # gaming
    "gaming",
    "fps",
    "stabil",
    "anti_lag",

    # kamera
    "tajam",
    "jernih",
    "detail",
    "bagusnya",
    "bening",

    # baterai
    "awet",
    "irit",
    "tahan",
    "fastcharge",

    # layar
    "amoled",
    "cerah",
    "refresh",

    # fitur
    "lengkap",
    "premium",
    "unggul",

    # rekomendasi
    "rekomendasi",
    "recommended",
    "favorit"
}

In [4]:
negatif = {

    # umum
    "jelek",
    "buruk",
    "parah",
    "kecewa",

    # performa
    "lemot",
    "lag",
    "ngelag",
    "patah",
    "freeze",
    "stuck",

    # suhu
    "panas",
    "overheat",

    # baterai
    "boros",
    "drop",
    "cepat_habis",

    # kamera
    "blur",
    "buram",
    "gelap",
    "noise",

    # layar
    "ghost_touch",
    "pecah",
    "retak",

    # sistem
    "bug",
    "error",
    "crash",

    # harga
    "mahal",
    "kemahalan",

    # kualitas
    "rusak",
    "cacat",
    "zonk",

    # pengalaman
    "nyesel",
    "mengecewakan"
}

In [5]:
def sentiment_rule(text):

    skor = 0

    kata = str(text).split()

    for k in kata:

        if k in positif:
            skor += 1

        elif k in negatif:
            skor -= 1

    if skor > 0:
        return "Positif"

    elif skor < 0:
        return "Negatif"

    else:
        return "Netral"

In [6]:
df["Sentiment_Rule"] = (
    df["Comment_Final"]
    .apply(sentiment_rule)
)

df["Sentiment_Rule"].value_counts()

Sentiment_Rule
Netral     5479
Positif    1506
Negatif     214
Name: count, dtype: int64

In [7]:
persen = (
    df["Sentiment_Rule"]
    .value_counts(normalize=True)
    * 100
).round(2)

print(persen)

Sentiment_Rule
Netral     76.11
Positif    20.92
Negatif     2.97
Name: proportion, dtype: float64

### Tampilkan Komentar Tiap Kelas

POSITIF

In [8]:
df[
    df["Sentiment_Rule"]=="Positif"
][
    ["Comment_Final","Sentiment_Rule"]
].sample(10)

                                          Comment_Final Sentiment_Rule
6396  rekomendasi versi 5jt samsung a06 si kencang m...        Positif
1830  kakak rekomendasi handphone oppo reno 5g oppo ...        Positif
4856  user xiaomi 14t pro hadirr mantep sihh 14t pro...        Positif
213     tahan iqoo z7 update tarik range gin audio jack        Positif
3477                         infinix hot pro plus bagus        Positif
4753      syang moto g45 masuk ya bagus dripada infinix        Positif
3311  rekomendasi handphone baterai spesifikasi luma...        Positif
2678                                      poco m7 bagus        Positif
4351  realme gt vs realme gt performa camera bagus y...        Positif
2701  rekomen handphone tecno bagus yaa pakai cewek ...        Positif

NEGATIF

In [9]:
df[
    df["Sentiment_Rule"]=="Negatif"
][
    ["Comment_Final","Sentiment_Rule"]
].sample(10)

                                          Comment_Final Sentiment_Rule
3381              si ipone main nominasi sisa buruk moa        Negatif
1149  ogah beli mahal z10r rekomen 3jt nett tanggal ...        Negatif
2789  hpnya limpah mbok ya handphone rusak rusak tom...        Negatif
4362  beli realme pro 5g skrng handphone rusak kena ...        Negatif
6575  poco x7p panas pakai x6p buruk dipake main cod...        Negatif
6135  handphone mahal rusak bosan mending beli handp...        Negatif
6434  nyesel beli realme gt gantiin ip13 grinning fa...        Negatif
5790  oppo reno reguler masuk milih reno sayang revi...        Negatif
1961  coba barusan pakai hdr kulit gelap pakai hdr h...        Negatif
1981  mksh bny berkat manteb beli reno and damn nyes...        Negatif

NETRAL

In [10]:
df[
    df["Sentiment_Rule"]=="Netral"
][
    ["Comment_Final","Sentiment_Rule"]
].sample(10)

                                          Comment_Final Sentiment_Rule
5378  banget handphone loe mereun giveaway face with...         Netral
3427                               riview advan matchaa         Netral
1661  advan upgrade comeback versi wahh tampil media...         Netral
3320       triple crown handphone cat with tears of joy         Netral
6651  alhamdulillah pakai tecno camon non pro beamin...         Netral
5737  range juta infinix hot 4g ghoib kalo harga 2jt...         Netral
3091  alhamdulillah kebel infinix hot 60pro grinning...         Netral
5047                                      poco f7 david         Netral
3305  manteb sa suka menang harga juta handphone adm...         Netral
4207  lihat review gadget in alhamdulillah kebel inf...         Netral

In [11]:
df.to_csv(
    "Model Rule Based.csv",
    index=False,
    encoding="utf-8-sig"
)

print("✅ Model Rule Based.csv tersimpan")

✅ Model Rule Based.csv tersimpan